<html>
#این تغیییرات برای تست در تمرین هشتم دکتر امامی است
#محمد اسماعیل فیروزیان با شماره دانشجویی 9911126076 داشنجو رشته مهندسی کامپبوتر  در دانشگاه سمنان
#با تشکر از توجه شما
<head>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" >
</head>
<body>
<div style="width:50%;margin:0 auto"  class="panel panel-default" >
<div  class="panel-heading" style="direction:rtl" >دیدگاه شما</div>
  <div class="panel-body">
  	<form method="post">
  	  <div class="form-group" style="direction:rtl">
	    <label for="exampleInputEmail1"  >نام و نام خانوادگی</label>
	    <input type="text" name="name" class="form-control" id="exampleInputEmail1" placeholder="نام و نام خانوادگی خود را وارد کنید" style="direction:rtl">
	  </div>
	  <div class="form-group"style="direction:rtl">
	    <label for="exampleInputEmail1" >ایمیل</label>
	    <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="ایمیل خود را وارد کنید"style="direction:rtl">
	  </div>
	  <div class="form-group" style="direction:rtl">
	    <label for="exampleInputPassword1" >عنوان</label>
	    <textarea name="subject" class="form-control" rows="3"></textarea>
	  </div>
<div style="direction:rtl">
	  <button type="تایید" class="btn btn-primary">تایید</button>
</div>
	</form>
  </div>
</div>
</body>
</html>
